{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0853dfb9-7600-4049-b3f5-72fb0e5e5d68",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.model_selection import train_test_split\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "22f03660-049a-4614-b48d-814c681750ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load data\n",
    "df = pd.read_csv(\"customer.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "9e260a92-4e2b-43be-8275-b6cf19a0d141",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 7043 entries, 0 to 7042\n",
      "Data columns (total 20 columns):\n",
      " #   Column            Non-Null Count  Dtype  \n",
      "---  ------            --------------  -----  \n",
      " 0   gender            7043 non-null   object \n",
      " 1   SeniorCitizen     7043 non-null   int64  \n",
      " 2   Partner           7043 non-null   object \n",
      " 3   Dependents        7043 non-null   object \n",
      " 4   tenure            7043 non-null   int64  \n",
      " 5   PhoneService      7043 non-null   object \n",
      " 6   MultipleLines     7043 non-null   object \n",
      " 7   InternetService   7043 non-null   object \n",
      " 8   OnlineSecurity    7043 non-null   object \n",
      " 9   OnlineBackup      7043 non-null   object \n",
      " 10  DeviceProtection  7043 non-null   object \n",
      " 11  TechSupport       7043 non-null   object \n",
      " 12  StreamingTV       7043 non-null   object \n",
      " 13  StreamingMovies   7043 non-null   object \n",
      " 14  Contract          7043 non-null   object \n",
      " 15  PaperlessBilling  7043 non-null   object \n",
      " 16  PaymentMethod     7043 non-null   object \n",
      " 17  MonthlyCharges    7043 non-null   float64\n",
      " 18  TotalCharges      7032 non-null   float64\n",
      " 19  Churn             7043 non-null   object \n",
      "dtypes: float64(2), int64(2), object(16)\n",
      "memory usage: 1.1+ MB\n"
     ]
    }
   ],
   "source": [
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "9f8a02ec-7263-453d-9741-b0eee0ed326f",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "df[\"TotalCharges\"] = pd.to_numeric(df[\"TotalCharges\"], errors=\"coerce\")\n",
    "\n",
    "# Only fill numeric columns with their mean\n",
    "numeric_columns = df.select_dtypes(include=['number']).columns\n",
    "df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].mean())\n",
    "\n",
    "# Convert target\n",
    "df[\"Churn\"] = df[\"Churn\"].map({\"Yes\": 1, \"No\": 0})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "7de71429-49c7-45f9-8bbc-27f21f649cd6",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\adithiyha\\anaconda\\Lib\\site-packages\\sklearn\\linear_model\\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n",
      "2026-01-18 11:55:23.349 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.409 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\adithiyha\\anaconda\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-01-18 11:55:23.410 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.411 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.412 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.413 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.414 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.415 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.419 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.421 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.422 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.426 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "C:\\Users\\adithiyha\\AppData\\Local\\Temp\\ipykernel_6648\\1009148386.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.\n",
      "  input_data[:] = 0\n",
      "2026-01-18 11:55:23.444 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-18 11:55:23.448 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "# Encode\n",
    "df_encoded = pd.get_dummies(df, drop_first=True)\n",
    "\n",
    "# Split\n",
    "X = df_encoded.drop(\"Churn\", axis=1)\n",
    "y = df_encoded[\"Churn\"]\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=42\n",
    ")\n",
    "\n",
    "# Train model\n",
    "model = LogisticRegression(max_iter=1000)\n",
    "model.fit(X_train, y_train)\n",
    "\n",
    "# -------- STREAMLIT UI --------\n",
    "\n",
    "st.title(\"📉 Customer Churn Prediction App\")\n",
    "st.write(\"Enter customer details to predict churn\")\n",
    "\n",
    "tenure = st.slider(\"Tenure (months)\", 0, 72, 12)\n",
    "monthly_charges = st.slider(\"Monthly Charges\", 0.0, 150.0, 70.0)\n",
    "total_charges = st.slider(\"Total Charges\", 0.0, 10000.0, 1000.0)\n",
    "\n",
    "# Create input with correct columns\n",
    "input_data = X.iloc[0:1].copy()\n",
    "input_data[:] = 0\n",
    "\n",
    "if \"tenure\" in input_data.columns:\n",
    "    input_data[\"tenure\"] = tenure\n",
    "if \"MonthlyCharges\" in input_data.columns:\n",
    "    input_data[\"MonthlyCharges\"] = monthly_charges\n",
    "if \"TotalCharges\" in input_data.columns:\n",
    "    input_data[\"TotalCharges\"] = total_charges\n",
    "\n",
    "# Predict\n",
    "if st.button(\"Predict Churn\"):\n",
    "    prediction = model.predict(input_data)\n",
    "\n",
    "    if prediction[0] == 1:\n",
    "        st.error(\"❌ Customer is likely to CHURN\")\n",
    "    else:\n",
    "        st.success(\"✅ Customer is likely to STAY\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7a172819-103c-4b09-9757-e9dbf0666d83",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
